export const samples = {
  series: {title:'The Silent Orbit', subtitle:'Some distances cannot be measured.', kind:'Series', year:'2025', length:'2 seasons · 16 episodes', status:'Returning series', creator:'Created by Lena Hart', summary:'A lone transmission draws a crew of strangers to a station at the edge of known space. As they piece together the lives of its missing inhabitants, they discover that the signal may be a memory of something that hasn’t happened yet.', score:'86', count:'12.4k', progress:5, total:16, unit:'episodes', action:'Watching', next:'S01 E06 · The other side of silence', nextMeta:'48 min · 3 episodes left in season 1', tags:['Space exploration','Found family','Slow burn','Mystery'], facts:[['Format','Scripted series'],['Episode length','48 minutes'],['Release','September 2025'],['Studio','Northlight Pictures'],['Original language','English']], chapters:['A signal in the dark','The things we left behind','A room without windows','Low orbit','The long way home','The other side of silence','An ocean between us','First light'], people:['Maya Chen','Elias Voss','Nora Okafor'], roles:['As Dr. Sera Vale','As Captain Rhys','As June Adeyemi'], color:'#64bebc'},
  movie: {title:'Beyond the Blue', subtitle:'Every journey leaves a trace.', kind:'Movie', year:'2024', length:'2h 08m', status:'Released', creator:'A film by Sofia Laurent', summary:'When an oceanographer returns to the remote island where she grew up, a discovery beneath the tide pulls her into an unlikely friendship. A quietly sweeping story about the places we leave, the people we remember, and finding our way back.', score:'89', count:'24.8k', progress:0, total:1, unit:'watches', action:'Planning', next:'Your next movie night', nextMeta:'128 minutes · One story, worth slowing down for', tags:['Ocean','Homecoming','Bittersweet','Beautiful cinematography'], facts:[['Format','Feature film'],['Runtime','128 minutes'],['Release','June 2024'],['Studio','Tidewater Films'],['Original language','English, French']], chapters:['The making of Beyond the Blue','Designing the island','A conversation with the director'], people:['Isabelle Moreau','Theo Park','Amara Ellis'], roles:['As Claire','As Daniel','As Simone'], color:'#7ab4d9'},
  game: {title:'Echoes of Elsewhere', subtitle:'Get lost. Find something worth keeping.', kind:'Game', year:'2025', length:'18h main story', status:'Released', creator:'Developed by Moss & Moon', summary:'Chart a forgotten archipelago where the stars have fallen into the sea. Sail between hand-crafted islands, make a home for a peculiar crew, and uncover the stories hiding just below the surface in this gentle exploration adventure.', score:'92', count:'8.6k', progress:7, total:24, unit:'achievements', action:'Playing', next:'Continue your expedition', nextMeta:'6.2 hours played · Last session yesterday', tags:['Exploration','Atmospheric','Single player','Cozy'], facts:[['Format','Adventure RPG'],['Platforms','PC · Steam Deck'],['Release','March 2025'],['Developer','Moss & Moon'],['Play time','18–30 hours']], chapters:['A place to call home','Cartographer','The lantern keeper','Follow the falling stars','Across the quiet sea','Leave no stone unturned'], people:['Moss & Moon','Rae Watanabe','Oliver Vale'], roles:['Development','Art direction','Original soundtrack'], color:'#b5b68a'},
  book: {title:'A Map of Quiet Places', subtitle:'There is more than one way to come home.', kind:'Book', year:'2023', length:'352 pages', status:'Published', creator:'Written by Elin Rivers', summary:'A cartographer inherits an atlas of places that no longer exist. Following its notes through coastal towns and forgotten landscapes, she begins to understand the extraordinary life of the woman who drew it, and the unfinished story they share.', score:'88', count:'6.2k', progress:124, total:352, unit:'pages', action:'Reading', next:'Pick up where you left off', nextMeta:'Page 124 · Chapter 9, The disappearing coast', tags:['Literary fiction','Magical realism','Travel','Reflective'], facts:[['Format','Novel · Hardcover'],['Length','352 pages'],['Published','October 2023'],['Publisher','Fern House'],['Original language','English']], chapters:['Part I · The inheritance','Part II · An atlas of absences','Part III · The disappearing coast','Part IV · A place of our own'], people:['Elin Rivers','Ada Finch','Fern House'], roles:['Author','Cover illustration','Publisher'], color:'#d5af86'},
};
export type SampleKey = keyof typeof samples;
// Original procedural art keeps the mockups independent of external services.
export function artwork(color:string, variant=0) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1600" height="900" viewBox="0 0 1600 900"><defs><linearGradient id="sky" x2="0" y2="1"><stop stop-color="#101d32"/><stop offset=".6" stop-color="${color}"/><stop offset="1" stop-color="#e8cfab"/></linearGradient><linearGradient id="water" x2="0" y2="1"><stop stop-color="${color}"/><stop offset="1" stop-color="#101e2e"/></linearGradient><radialGradient id="glow"><stop stop-color="#f5e4ca" stop-opacity=".6"/><stop offset="1" stop-color="#f5e4ca" stop-opacity="0"/></radialGradient></defs><path fill="url(#sky)" d="M0 0h1600v900H0z"/><ellipse cx="1000" cy="335" rx="480" ry="370" fill="url(#glow)"/><circle cx="${1000+variant*65}" cy="290" r="140" fill="#eddfc8" opacity=".8"/><circle cx="${960+variant*65}" cy="258" r="140" fill="#788f96" opacity=".55"/><path d="M0 540L190 440 290 470 510 320 710 540 900 470 1060 545 1300 365 1600 510V900H0" fill="#344e5a"/><path d="M0 602L210 545 395 590 600 465 845 625 1090 505 1410 600 1600 470V900H0" fill="#203b49"/><path d="M0 640Q440 590 800 640T1600 630V900H0" fill="url(#water)"/><g stroke="#e4d7bd" opacity=".25">${Array.from({length:24},(_,i)=>`<path d="M${700-i*12} ${650+i*9}h${330+i*22}"/>`).join('')}</g><path d="M0 850L260 735 460 815 650 790 910 900H0" fill="#101d2a"/><path d="M1150 900l170-110 280-65v175" fill="#13252e"/><path d="M350 764v-44m-8 16h16m-14 28 6-18 7 18" stroke="#eee5d4" stroke-width="4"/><g fill="#fff" opacity=".55"><circle cx="220" cy="100" r="2"/><circle cx="650" cy="150" r="2"/><circle cx="1250" cy="90" r="2"/><circle cx="460" cy="240" r="1.5"/></g></svg>`;
  return `data:image/svg+xml,${encodeURIComponent(svg)}`;
}
